create index AR.IDX_SALESFORCE_SITES_ALL_01 on AR.HZ_CUST_ACCT_SITES_ALL("STATUS","CUST_ACCOUNT_ID","CUST_ACCT_SITE_ID");
create index AR.IDX_SALESFORCE_USES_ALL_01 on AR.HZ_CUST_SITE_USES_ALL("SITE_USE_CODE","CUST_ACCT_SITE_ID","SITE_USE_ID");
