create index INV.IDX_SALESFORCE_PRDPRJ_01 on INV.MTL_SYSTEM_ITEMS_B("ORGANIZATION_ID","SEGMENT1","INVENTORY_ITEM_ID");
create index INV.IDX_STK_ZERO_14 on INV.MTL_SYSTEM_ITEMS_B("ORGANIZATION_ID","SEGMENT1","INVENTORY_ITEM_ID");
create index INV.IDX_STK_ZERO_02 on INV.MTL_SYSTEM_ITEMS_B("ATTRIBUTE9","ORGANIZATION_ID","SEGMENT1","INVENTORY_ITEM_ID");
