CREATE OR REPLACE SYNONYM APPSR.CONSULTA_PRODUTO_PT_V FOR APPS.CONSULTA_PRODUTO_PT_V;
CREATE OR REPLACE SYNONYM APPSR.XXPB_ESTOQUE_API_ZERO FOR XXPB.XXPB_ESTOQUE_API_ZERO#;
CREATE OR REPLACE SYNONYM APPSR.XXPB_ESTOQUE_API FOR XXPB.XXPB_ESTOQUE_API#;