CREATE OR REPLACE SYNONYM APPS.XXPB_ESTOQUE_API_ZERO FOR XXPB.XXPB_ESTOQUE_API_ZERO#;
CREATE OR REPLACE SYNONYM APPS.OM_SALDO_PRODUTO_ATP_POINTER FOR XXPB.OM_SALDO_PRODUTO_ATP_POINTER;
CREATE OR REPLACE SYNONYM APPS.OM_SALDO_PRODUTO_ATP_HIS_POINTER FOR XXPB.OM_SALDO_PRODUTO_ATP_HIS_POINTER;
CREATE OR REPLACE SYNONYM APPS.TMP_PROJETADO_SALESFORCE FOR XXPB.TMP_PROJETADO_SALESFORCE;
CREATE OR REPLACE SYNONYM APPS.XXPB_ORDER_API_SALESFORCE_LOGS FOR XXPB.XXPB_ORDER_API_SALESFORCE_LOGS#;
CREATE OR REPLACE SYNONYM APPS.XXPB_PO_SALESFORCE_CTRL FOR XXPB.XXPB_PO_SALESFORCE_CTRL#;