CREATE OR REPLACE SYNONYM APPS.XXPB_ESTOQUE_API_ZERO FOR XXPB.XXPB_ESTOQUE_API_ZERO#;
CREATE OR REPLACE SYNONYM APPSR.XXPB_ESTOQUE_API_ZERO FOR XXPB.XXPB_ESTOQUE_API_ZERO#;
CREATE OR REPLACE SYNONYM APPSR.XXPB_ESTOQUE_API FOR XXPB.XXPB_ESTOQUE_API#;