CREATE TABLE XXPB.OM_SALDO_PRODUTO_ATP_POINTER
(
  INVENTORY_ITEM_ID           NUMBER            NOT NULL,
  ITEM_UM                     VARCHAR2(5 BYTE)  NOT NULL,
  ID_PERIODO                  NUMBER            NOT NULL,
  ID_DEPOSITO                 NUMBER            NOT NULL,
  QT_PROGRAMADA_PRODUCAO      NUMBER,
  QT_CARTEIRA_PEDIDO          NUMBER,
  QT_SALDO                    NUMBER,
  CREATION_DATE               DATE              NOT NULL,
  CREATED_BY                  NUMBER            NOT NULL,
  LAST_UPDATE_DATE            DATE              NOT NULL,
  LAST_UPDATED_BY             NUMBER            NOT NULL,
  QT_SALDO_NEG               NUMBER
)
TABLESPACE APPS_TS_TX_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;



CREATE UNIQUE INDEX XXPB.OM_SALDO_PRODUTO_ATP_POINTER_PK ON XXPB.OM_SALDO_PRODUTO_ATP_POINTER
(INVENTORY_ITEM_ID, ITEM_UM, ID_PERIODO)
LOGGING
TABLESPACE APPS_TS_TX_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;

CREATE UNIQUE INDEX XXPB.OM_SALDO_PRODUTO_ATP_POINTER_PK_2 ON XXPB.OM_SALDO_PRODUTO_ATP_POINTER
(INVENTORY_ITEM_ID, ITEM_UM, ID_PERIODO, ID_DEPOSITO)
LOGGING
TABLESPACE APPS_TS_TX_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;

GRANT SELECT ON XXPB.OM_SALDO_PRODUTO_ATP_POINTER TO APPSR;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON XXPB.OM_SALDO_PRODUTO_ATP_POINTER TO XXPB WITH GRANT OPTION;

ALTER TABLE XXPB.OM_SALDO_PRODUTO_ATP_POINTER ADD (
  CONSTRAINT OM_SALDO_PRODUTO_ATP_POINTER_PK_2
  PRIMARY KEY
  (INVENTORY_ITEM_ID, ITEM_UM, ID_PERIODO, ID_DEPOSITO)
  USING INDEX XXPB.OM_SALDO_PRODUTO_ATP_POINTER_PK_2
  ENABLE VALIDATE);
