DROP TABLE XXPB.XXPB_ORDER_API_SALESFORCE_LOGS;

CREATE TABLE XXPB.XXPB_ORDER_API_SALESFORCE_LOGS
(
  MESSAGE          VARCHAR2(4000 BYTE),
  LOG_TYPE         NUMBER                       NOT NULL,
  CONC_REQUEST_ID  NUMBER,
  CREATION_DATE    DATE,
  CREATION_BY      NUMBER,
  SOURCE_HDR_ID    VARCHAR2(50 BYTE),
  SOURCE_LIN_ID    NUMBER,
  REQUEST_JSON     BLOB
)
TABLESPACE APPS_TS_TX_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN XXPB.XXPB_ORDER_API_SALESFORCE_LOGS.MESSAGE IS 'Campo destinado a mensagem de processamento';

COMMENT ON COLUMN XXPB.XXPB_ORDER_API_SALESFORCE_LOGS.LOG_TYPE IS 'Campo destinado a classificacao de tipo de registro/mensagem - 0-Pendente 1-Sucesso 2-Erro';

COMMENT ON COLUMN XXPB.XXPB_ORDER_API_SALESFORCE_LOGS.CONC_REQUEST_ID IS 'Campo destinado ao ID do processo concorrente';

COMMENT ON COLUMN XXPB.XXPB_ORDER_API_SALESFORCE_LOGS.CREATION_DATE IS 'Campo destinado a data de criacao/processamento';

COMMENT ON COLUMN XXPB.XXPB_ORDER_API_SALESFORCE_LOGS.CREATION_BY IS 'Campo destinado ao ID do usuario executor do processo';



CREATE INDEX XXPB.XXPB_ORDER_API_SALESFORCE_LOG_N3 ON XXPB.XXPB_ORDER_API_SALESFORCE_LOGS
(CONC_REQUEST_ID)
LOGGING
TABLESPACE APPS_TS_TX_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX XXPB.XXPB_ORDER_API_SALESFORCE_LOG_N4 ON XXPB.XXPB_ORDER_API_SALESFORCE_LOGS
(LOG_TYPE)
LOGGING
TABLESPACE APPS_TS_TX_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE ON XXPB.XXPB_ORDER_API_SALESFORCE_LOGS TO APPS WITH GRANT OPTION;

GRANT SELECT ON XXPB.XXPB_ORDER_API_SALESFORCE_LOGS TO APPSR;

GRANT SELECT ON XXPB.XXPB_ORDER_API_SALESFORCE_LOGS TO XXISV;


/* Formatted on 29/03/2022 17:05:44 (QP5 v5.215.12089.38647) */
CREATE OR REPLACE VIEW XXPB.XXPB_ORDER_API_SALESFORCE_LOGS#
(
   MESSAGE,
   LOG_TYPE,
   CONC_REQUEST_ID,
   CREATION_DATE,
   CREATION_BY,
   SOURCE_HDR_ID,
   SOURCE_LIN_ID
)
AS
   SELECT MESSAGE MESSAGE,
          LOG_TYPE LOG_TYPE,
          CONC_REQUEST_ID CONC_REQUEST_ID,
          CREATION_DATE CREATION_DATE,
          CREATION_BY CREATION_BY,
          SOURCE_HDR_ID SOURCE_HDR_ID,
          SOURCE_LIN_ID SOURCE_LIN_ID
     FROM "XXPB"."XXPB_ORDER_API_SALESFORCE_LOGS";



GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE ON XXPB.XXPB_ORDER_API_SALESFORCE_LOGS# TO APPS WITH GRANT OPTION;

GRANT SELECT ON XXPB.XXPB_ORDER_API_SALESFORCE_LOGS# TO APPSR;

GRANT SELECT ON XXPB.XXPB_ORDER_API_SALESFORCE_LOGS# TO XXISV;



