CREATE TABLE XXPB.XXPB_PO_SALESFORCE_CTRL
(
  ORDER_SOURCE   VARCHAR2(30 BYTE),
  SOURCE_HDR_ID  VARCHAR2(50 BYTE)
)
TABLESPACE APPS_TS_TX_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX XXPB.XXPB_PO_SALESFORCE_CTRL_01PB ON XXPB.XXPB_PO_SALESFORCE_CTRL
(ORDER_SOURCE, SOURCE_HDR_ID)
LOGGING
TABLESPACE APPS_TS_TX_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, READ, DEBUG, FLASHBACK ON XXPB.XXPB_PO_SALESFORCE_CTRL TO APPS WITH GRANT OPTION;

GRANT SELECT ON XXPB.XXPB_PO_SALESFORCE_CTRL TO APPSR;

GRANT SELECT ON XXPB.XXPB_PO_SALESFORCE_CTRL TO XXISV;



/* Formatted on 29/03/2022 16:44:52 (QP5 v5.215.12089.38647) */
CREATE OR REPLACE VIEW XXPB.XXPB_PO_SALESFORCE_CTRL#
(
   ORDER_SOURCE,
   SOURCE_HDR_ID
)
AS
   SELECT ORDER_SOURCE ORDER_SOURCE, SOURCE_HDR_ID SOURCE_HDR_ID
     FROM "XXPB"."XXPB_PO_SALESFORCE_CTRL";


GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE, READ, DEBUG ON XXPB.XXPB_PO_SALESFORCE_CTRL# TO APPS WITH GRANT OPTION;

GRANT SELECT ON XXPB.XXPB_PO_SALESFORCE_CTRL# TO APPSR;

GRANT SELECT ON XXPB.XXPB_PO_SALESFORCE_CTRL# TO XXISV;



