CREATE TABLE XXPB.TMP_PROJETADO_SALESFORCE
(
  DES_CD      VARCHAR2(10 BYTE),
  COD_ITEM    VARCHAR2(20 BYTE),
  LAST_UPDATE_DATE DATE,
  SHOP_P1     NUMBER,
  SHOP_P2     NUMBER,
  SHOP_P3     NUMBER,
  SHOP_P4     NUMBER,
  SHOP_P5     NUMBER,
  SHOP_P6     NUMBER,
  SHOP_P7     NUMBER,
  SHOP_P8     NUMBER,
  SHOP_P9     NUMBER,
  SHOP_P10    NUMBER,
  DES_CD_1    VARCHAR2(10 BYTE),
  COD_ITEM_1  VARCHAR2(20 BYTE),
  LAST_UPDATE_DATE_1 DATE,
  PTBL_P1     NUMBER,
  PTBL_P2     NUMBER,
  PTBL_P3     NUMBER,
  PTBL_P4     NUMBER,
  PTBL_P5     NUMBER,
  PTBL_P6     NUMBER,
  PTBL_P7     NUMBER,
  PTBL_P8     NUMBER,
  PTBL_P9     NUMBER,
  PTBL_P10    NUMBER,
  BALANCE__C  NUMBER,
  EXPORTBALANCE__C NUMBER,
  BALANCEPORTOBELLOSHOP__C NUMBER,
  SALDO_ZERO  INT 
)
TABLESPACE APPS_TS_TX_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX XXPB.IDX_ITEM_SALESFORCE ON XXPB.TMP_PROJETADO_SALESFORCE
(COD_ITEM)
LOGGING
TABLESPACE APPS_TS_TX_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE, DEBUG, FLASHBACK ON XXPB.TMP_PROJETADO_SALESFORCE TO APPSR;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE, DEBUG, FLASHBACK ON XXPB.TMP_PROJETADO_SALESFORCE TO APPS;


CREATE TABLE XXPB.OM_SALDO_PRODUTO_ATP_HIS_POINTER
(
  INVENTORY_ITEM_ID           NUMBER            NOT NULL,
  ITEM_UM                     VARCHAR2(5 BYTE)  NOT NULL,
  ID_PERIODO                  NUMBER            NOT NULL,
  ID_DEPOSITO		      NUMBER            NOT NULL, 
  DT_HISTORICO                DATE              NOT NULL,
  QT_PROGRAMADA_PRODUCAO      NUMBER,
  QT_CARTEIRA_PEDIDO          NUMBER,
  QT_SALDO                    NUMBER,
  CREATION_DATE               DATE              NOT NULL,
  CREATED_BY                  NUMBER            NOT NULL,
  LAST_UPDATE_DATE            DATE              NOT NULL,
  LAST_UPDATED_BY             NUMBER            NOT NULL,
  QT_SALDO_NEG                NUMBER
)
TABLESPACE APPS_TS_TX_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

GRANT SELECT ON XXPB.OM_SALDO_PRODUTO_ATP_HIS_POINTER TO APPSR;

GRANT SELECT ON XXPB.OM_SALDO_PRODUTO_ATP_HIS_POINTER TO XXPB;



CREATE TABLE XXPB.OM_SALDO_PRODUTO_ATP_POINTER
(
  INVENTORY_ITEM_ID           NUMBER            NOT NULL,
  ITEM_UM                     VARCHAR2(5 BYTE)  NOT NULL,
  ID_PERIODO                  NUMBER            NOT NULL,
  ID_DEPOSITO                 NUMBER            NOT NULL,
  QT_PROGRAMADA_PRODUCAO      NUMBER,
  QT_CARTEIRA_PEDIDO          NUMBER,
  QT_SALDO                    NUMBER,
  CREATION_DATE               DATE              NOT NULL,
  CREATED_BY                  NUMBER            NOT NULL,
  LAST_UPDATE_DATE            DATE              NOT NULL,
  LAST_UPDATED_BY             NUMBER            NOT NULL,
  QT_SALDO_NEG               NUMBER
)
TABLESPACE APPS_TS_TX_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;



CREATE UNIQUE INDEX XXPB.OM_SALDO_PRODUTO_ATP_POINTER_PK ON XXPB.OM_SALDO_PRODUTO_ATP_POINTER
(INVENTORY_ITEM_ID, ITEM_UM, ID_PERIODO)
LOGGING
TABLESPACE APPS_TS_TX_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;

CREATE UNIQUE INDEX XXPB.OM_SALDO_PRODUTO_ATP_POINTER_PK_2 ON XXPB.OM_SALDO_PRODUTO_ATP_POINTER
(INVENTORY_ITEM_ID, ITEM_UM, ID_PERIODO, ID_DEPOSITO)
LOGGING
TABLESPACE APPS_TS_TX_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;

GRANT SELECT ON XXPB.OM_SALDO_PRODUTO_ATP_POINTER TO APPSR;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON XXPB.OM_SALDO_PRODUTO_ATP_POINTER TO XXPB WITH GRANT OPTION;

ALTER TABLE XXPB.OM_SALDO_PRODUTO_ATP_POINTER ADD (
  CONSTRAINT OM_SALDO_PRODUTO_ATP_POINTER_PK_2
  PRIMARY KEY
  (INVENTORY_ITEM_ID, ITEM_UM, ID_PERIODO, ID_DEPOSITO)
  USING INDEX XXPB.OM_SALDO_PRODUTO_ATP_POINTER_PK_2
  ENABLE VALIDATE);


CREATE TABLE XXPB.XXPB_ESTOQUE_API_ZERO
(
  INVENTORY_ITEM_ID       NUMBER,
  COD_DEPOSITO            VARCHAR2(5 BYTE),
  COD_TONALIDADE_CALIBRE  VARCHAR2(20 BYTE),
  COD_PRODUTO_ORA         VARCHAR2(30 BYTE),
  LAST_UPDATE_DATE        DATE,
  FLAG_STK                INT,
  FLAG_EXC    			  INT     
)
TABLESPACE APPS_TS_TX_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE OR REPLACE EDITIONING VIEW XXPB.XXPB_ESTOQUE_API_ZERO#
(
   INVENTORY_ITEM_ID,
   COD_DEPOSITO,
   COD_TONALIDADE_CALIBRE,
   COD_PRODUTO_ORA,
   LAST_UPDATE_DATE,
   FLAG_STK,
   FLAG_EXC 
)
AS
   SELECT INVENTORY_ITEM_ID INVENTORY_ITEM_ID,
          COD_DEPOSITO COD_DEPOSITO,
          COD_TONALIDADE_CALIBRE COD_TONALIDADE_CALIBRE,
          COD_PRODUTO_ORA COD_PRODUTO_ORA,
          LAST_UPDATE_DATE LAST_UPDATE_DATE,
		  FLAG_STK FLAG_STK,
		  FLAG_EXC FLAG_EXC
     FROM "XXPB"."XXPB_ESTOQUE_API_ZERO";



DROP TABLE XXPB.XXPB_ORDER_API_SALESFORCE_LOGS;

CREATE TABLE XXPB.XXPB_ORDER_API_SALESFORCE_LOGS
(
  MESSAGE          VARCHAR2(4000 BYTE),
  LOG_TYPE         NUMBER                       NOT NULL,
  CONC_REQUEST_ID  NUMBER,
  CREATION_DATE    DATE,
  CREATION_BY      NUMBER,
  SOURCE_HDR_ID    VARCHAR2(50 BYTE),
  SOURCE_LIN_ID    NUMBER,
  REQUEST_JSON     BLOB
)
TABLESPACE APPS_TS_TX_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN XXPB.XXPB_ORDER_API_SALESFORCE_LOGS.MESSAGE IS 'Campo destinado a mensagem de processamento';

COMMENT ON COLUMN XXPB.XXPB_ORDER_API_SALESFORCE_LOGS.LOG_TYPE IS 'Campo destinado a classificacao de tipo de registro/mensagem - 0-Pendente 1-Sucesso 2-Erro';

COMMENT ON COLUMN XXPB.XXPB_ORDER_API_SALESFORCE_LOGS.CONC_REQUEST_ID IS 'Campo destinado ao ID do processo concorrente';

COMMENT ON COLUMN XXPB.XXPB_ORDER_API_SALESFORCE_LOGS.CREATION_DATE IS 'Campo destinado a data de criacao/processamento';

COMMENT ON COLUMN XXPB.XXPB_ORDER_API_SALESFORCE_LOGS.CREATION_BY IS 'Campo destinado ao ID do usuario executor do processo';



CREATE INDEX XXPB.XXPB_ORDER_API_SALESFORCE_LOG_N3 ON XXPB.XXPB_ORDER_API_SALESFORCE_LOGS
(CONC_REQUEST_ID)
LOGGING
TABLESPACE APPS_TS_TX_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX XXPB.XXPB_ORDER_API_SALESFORCE_LOG_N4 ON XXPB.XXPB_ORDER_API_SALESFORCE_LOGS
(LOG_TYPE)
LOGGING
TABLESPACE APPS_TS_TX_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE ON XXPB.XXPB_ORDER_API_SALESFORCE_LOGS TO APPS WITH GRANT OPTION;

GRANT SELECT ON XXPB.XXPB_ORDER_API_SALESFORCE_LOGS TO APPSR;

GRANT SELECT ON XXPB.XXPB_ORDER_API_SALESFORCE_LOGS TO XXISV;


/* Formatted on 29/03/2022 17:05:44 (QP5 v5.215.12089.38647) */
CREATE OR REPLACE VIEW XXPB.XXPB_ORDER_API_SALESFORCE_LOGS#
(
   MESSAGE,
   LOG_TYPE,
   CONC_REQUEST_ID,
   CREATION_DATE,
   CREATION_BY,
   SOURCE_HDR_ID,
   SOURCE_LIN_ID
)
AS
   SELECT MESSAGE MESSAGE,
          LOG_TYPE LOG_TYPE,
          CONC_REQUEST_ID CONC_REQUEST_ID,
          CREATION_DATE CREATION_DATE,
          CREATION_BY CREATION_BY,
          SOURCE_HDR_ID SOURCE_HDR_ID,
          SOURCE_LIN_ID SOURCE_LIN_ID
     FROM "XXPB"."XXPB_ORDER_API_SALESFORCE_LOGS";



GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE ON XXPB.XXPB_ORDER_API_SALESFORCE_LOGS# TO APPS WITH GRANT OPTION;

GRANT SELECT ON XXPB.XXPB_ORDER_API_SALESFORCE_LOGS# TO APPSR;

GRANT SELECT ON XXPB.XXPB_ORDER_API_SALESFORCE_LOGS# TO XXISV;



CREATE TABLE XXPB.XXPB_PO_SALESFORCE_CTRL
(
  ORDER_SOURCE   VARCHAR2(30 BYTE),
  SOURCE_HDR_ID  VARCHAR2(50 BYTE)
)
TABLESPACE APPS_TS_TX_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX XXPB.XXPB_PO_SALESFORCE_CTRL_01PB ON XXPB.XXPB_PO_SALESFORCE_CTRL
(ORDER_SOURCE, SOURCE_HDR_ID)
LOGGING
TABLESPACE APPS_TS_TX_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, READ, DEBUG, FLASHBACK ON XXPB.XXPB_PO_SALESFORCE_CTRL TO APPS WITH GRANT OPTION;

GRANT SELECT ON XXPB.XXPB_PO_SALESFORCE_CTRL TO APPSR;

GRANT SELECT ON XXPB.XXPB_PO_SALESFORCE_CTRL TO XXISV;



/* Formatted on 29/03/2022 16:44:52 (QP5 v5.215.12089.38647) */
CREATE OR REPLACE VIEW XXPB.XXPB_PO_SALESFORCE_CTRL#
(
   ORDER_SOURCE,
   SOURCE_HDR_ID
)
AS
   SELECT ORDER_SOURCE ORDER_SOURCE, SOURCE_HDR_ID SOURCE_HDR_ID
     FROM "XXPB"."XXPB_PO_SALESFORCE_CTRL";


GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE, READ, DEBUG ON XXPB.XXPB_PO_SALESFORCE_CTRL# TO APPS WITH GRANT OPTION;

GRANT SELECT ON XXPB.XXPB_PO_SALESFORCE_CTRL# TO APPSR;

GRANT SELECT ON XXPB.XXPB_PO_SALESFORCE_CTRL# TO XXISV;



