SELECT DESCRIPTION ds_conta_nacional,
       FLEX_VALUE cd_conta_nacional
FROM FND_FLEX_VALUES_VL 
WHERE FLEX_VALUE_SET_ID = (SELECT FLEX_VALUE_SET_ID FROM FND_FLEX_VALUE_SETS WHERE FLEX_VALUE_SET_NAME LIKE 'QP_CONTA_NACIONAL_APO')
  AND ENABLED_FLAG='Y'
ORDER BY DESCRIPTION
