DROP TABLE APPS.OM_SALDO_PRODUTO_ATP_HIS_POINTER;

CREATE TABLE APPS.OM_SALDO_PRODUTO_ATP_HIS_POINTER
(
  INVENTORY_ITEM_ID           NUMBER            NOT NULL,
  ITEM_UM                     VARCHAR2(5 BYTE)  NOT NULL,
  ID_PERIODO                  NUMBER            NOT NULL,
  ID_DEPOSITO		      NUMBER            NOT NULL, 
  DT_HISTORICO                DATE              NOT NULL,
  QT_PROGRAMADA_PRODUCAO      NUMBER,
  QT_CARTEIRA_PEDIDO          NUMBER,
  QT_SALDO                    NUMBER,
  CREATION_DATE               DATE              NOT NULL,
  CREATED_BY                  NUMBER            NOT NULL,
  LAST_UPDATE_DATE            DATE              NOT NULL,
  LAST_UPDATED_BY             NUMBER            NOT NULL,
  QT_SALDO_NEG                NUMBER
)
TABLESPACE APPS_TS_TX_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

GRANT SELECT ON APPS.OM_SALDO_PRODUTO_ATP_HIS_POINTER TO APPSR;

GRANT SELECT ON APPS.OM_SALDO_PRODUTO_ATP_HIS_POINTER TO XXISV;
